### PR TITLE
standardized buttons

### PR DESCRIPTION
**Pull request by mlemyco**

### CODE REVIEW

**Review by anastasia21112 — APPROVED** [review]
this is amazing! claps!

**Comment by josephchiang20** [comment]
nice!! Good stuff, can you just remove these buttons styles from the accordion on the "our programs" page, make it so that the when the background isn't grey, the color of the hover should change to white or whatever the background colour is (e.g. the 'get-involved' and 'keep me updated' buttons. Also, for some reason the 'select team' dropdown ono "About Us" is cut off. Once these changes are fixed, I will merge.

**Comment by mlemyco** [comment]
thats funny bcuz thats exactly what i thought was ugly and was tryna fix LMFAO

**Comment by josephchiang20** [comment]
One more thing, the select team dropdown on "about us" has the underline hover on it. Once that is fixed we are good to go!! You can do future changes on different pull requests

**Pull request merged**
